### ISSUE TITLE
[Bug]: The docs do not cleanly show the parameters and return values for each function

### ISSUE THREAD

**Issue by rbarman** [American-Soccer-Analysis/itscalledsoccer#166]
### What happened?

The docs do not cleanly show the parameters and return values for each function. For example, look at the reference for `get_game_xgoals` (https://american-soccer-analysis.github.io/itscalledsoccer/reference/#itscalledsoccer.client.AmericanSoccerAnalysis.get_game_xgoals). 

The description of the parameters and return values is in raw text:
`
:param leagues: Leagues on which to filter. Accepts a string or list of strings. :param kwargs: The following arguments will be parsed: game_ids: Game IDs on which to filter. Accepts a string or list of strings. season_name: Name(s)/year(s) of seasons. Cannot be combined with a date range. Accepts a string or list of strings. start_date: Start of a date range. Must be a string in YYYY-MM-DD format. Cannot be combined with season_name. end_date: End of a date range. Must be a string in YYYY-MM-DD format. Cannot be combined with season_name. stage_name: Describes the stage of competition in which a game took place. Accepts a string or list of strings. :returns: Dataframe
`

Screenshot of docs:

![image](https://github.com/American-Soccer-Analysis/itscalledsoccer/assets/5035882/1cc78168-b17f-44de-b375-c56f68656696)

---

The expected behavior is to have a structured output for the parameters and return values. For example, the MobFot docs (https://bgrnwd.com/mobfot/reference/#mobfot.client.MobFot.get_match_tv_listing) have a structured output where it easy to read the parameters and return values.

### Version

0.1.0

### What version of Python are you using?

Python 3.7.x

### What operating system are you using?

MacOS

**Comment by bgrnwd** [comment]
My hunch is we just need to switch the docstring syntax so `mkdocstrings` can parse it correctly
