### ISSUE TITLE
[Feature Request]: Don't load all entities on client initialization, consider lazy loading

### ISSUE THREAD

**Issue by bgrnwd** [American-Soccer-Analysis/itscalledsoccer#169]
### What feature would you like to see?

This this reduce the amount of time it takes to instantiate the client

**Comment by rbarman** [comment]
You can assign this to me. I just started working on this in my feature branch - https://github.com/rbarman/itscalledsoccer/tree/lazy_load_entities

**Comment by rbarman** [comment]
I think this can be closed now that the latest release (https://github.com/American-Soccer-Analysis/itscalledsoccer/releases/tag/v1.2.0) has these changes
