### ISSUE TITLE
[Feature Request]: Add test coverage

### ISSUE THREAD

**Issue by rbarman** [American-Soccer-Analysis/itscalledsoccer#181]
### What feature would you like to see?

Add a test coverage measure

**Value**
- Developers may work on complex features that require a lot of changes and and code refactoring. They will need to assess existing test cases and write new test cases. They need a quick way to ensure that all their new code is properly tested.
- Repo owners / PR approvers need a quick way to validate that new pull requests are introducing code that is properly tested and nothing is missing.
- Developers and repo owners currently do not have a clear way to evaluate this.

**Possible implementation**

Here is one way we could introduce test coverage

1) Leverage [pytest-cov](https://pypi.org/project/pytest-cov/) to generate [coverage reports](https://python-basics-tutorial.readthedocs.io/en/latest/test/coverage.html#generate-html-reports). Devs would run this locally while developing and validate that their new / changed code is properly tested.
2) Update current `python-tests.yml` github workflow to run `pytest-cov` and generate report. Then add [pytest-coverage-comment](https://github.com/marketplace/actions/pytest-coverage-comment) github action as next step which will create a comment with all coverage info. The approvers can review the comment if there is an acceptable coverage percentage

**Comment by bgrnwd** [comment]
I would be in favor of the second option and in addition to using `pytest-coverage-comment`, we should also upload to [Codecov](https://app.codecov.io/gh/American-Soccer-Analysis/itscalledsoccer).

**Comment by rbarman** [comment]
I have something working right now with `pytest-coverage-comment`. This PR on my fork has the coverage comment: https://github.com/rbarman/itscalledsoccer/pull/4#issuecomment-2226729865. So ideally the PR approver can judge if the coverage is sufficient and then approve/reject. Let me know your thoughts. The [changes](https://github.com/American-Soccer-Analysis/itscalledsoccer/compare/main...rbarman:itscalledsoccer:181-test-coverage) to set this up are pretty minimal so far. 

Sure. It looks like the R repo (https://github.com/American-Soccer-Analysis/itscalledsoccer-r) has codecov configured in its workflow. I can take a look at how that is setup

**Comment by bgrnwd** [comment]
I think it looks good! Would you mind opening a PR? We have `codecov` enabled for the R version of itscalledsoccer, so we can get it setup here too.
