### ISSUE TITLE
[Bug]: Querying with a list of game ids only returns first game id

### ISSUE THREAD

**Issue by EthanMarx** [American-Soccer-Analysis/itscalledsoccer#20]
### What happened?

xgoals = client.get_game_xgoals(leagues=leagues, game_ids=list(game_ids))

Will return a dataframe of length 1 regardless of how many game ids are in the list. 

### Version

0.1.1

### What version of Python or R are you using?

Python 3.7.x

### What operating system are you using?

MacOS

**Comment by bgrnwd** [comment]
Thanks for reporting this! Think I found the source of the bug and I'll have a fix out shortly.

**Comment by bgrnwd** [comment]
@EthanMarx Please upgrade to 0.1.3 and let me know if you still see the issue. To update run `pip install --upgrade itscalledsoccer`
