### ISSUE TITLE
Missing Players?

### ISSUE THREAD

**Issue by MAndrecovich** [American-Soccer-Analysis/itscalledsoccer#23]
### What happened?

Hi,

I'm playing around with this and notice there seems to be players missing when I try to do simple things like:

asa_client.get_players(ids = 'xW5pdnLY5g')
asa_client.get_players(name = 'Zlatan')

### Version

0.1.1

### What version of Python or R are you using?

Python 3.7.x

### What operating system are you using?

MacOS

### Relevant log output

```shell
asa_client.get_players(ids = 'xW5pdnLY5g')
```

**Comment by bgrnwd** [comment]
Thanks for reporting this! Think I found the source of the bug and I'll try and get a fix out this weekend.

**Comment by bgrnwd** [comment]
@MAndrecovich Got to this a bit quicker than I expected, give `0.1.4` a try and let me know if you that fixes it or if you still see the issue. To update run `pip install --upgrade itscalledsoccer`
